CREATE TABLE IF NOT EXISTS staging.stg_snapshot_manifest (
    manifest_row_id VARCHAR PRIMARY KEY,
    deployment_id VARCHAR NOT NULL,
    source_asset_id VARCHAR NOT NULL,
    snapshot_id VARCHAR NOT NULL,
    logical_source_name VARCHAR NOT NULL,
    relative_path VARCHAR NOT NULL,
    source_sha256 VARCHAR NOT NULL,
    canonical_schema_hash VARCHAR NOT NULL,
    row_count BIGINT NOT NULL,
    column_count BIGINT NOT NULL,
    source_run_id VARCHAR,
    source_model_version VARCHAR,
    process_timestamp TIMESTAMPTZ,
    observation_date DATE,
    reporting_date DATE,
    origination_date DATE,
    source_date_provenance VARCHAR NOT NULL,
    history_mode VARCHAR NOT NULL,
    evidence_classification VARCHAR NOT NULL,
    identity_continuity_status VARCHAR NOT NULL,
    temporal_quality VARCHAR NOT NULL,
    historical_analytics_eligible BOOLEAN NOT NULL,
    discovery_timestamp TIMESTAMP NOT NULL
);
