CREATE TABLE IF NOT EXISTS staging.stg_historical_snapshot_row (
    staging_row_id VARCHAR PRIMARY KEY,
    ingestion_batch_id VARCHAR NOT NULL,
    snapshot_id VARCHAR NOT NULL,
    source_asset_id VARCHAR NOT NULL,
    source_row_number BIGINT NOT NULL,
    history_mode VARCHAR NOT NULL,
    evidence_classification VARCHAR NOT NULL,
    source_entity_id VARCHAR,
    source_facility_id VARCHAR,
    observation_date DATE,
    reporting_date DATE,
    origination_date DATE,
    default_date DATE,
    cure_date DATE,
    recovery_date DATE,
    maturity_date DATE,
    source_run_id VARCHAR,
    source_model_version VARCHAR,
    pd DOUBLE,
    lgd DOUBLE,
    ead DOUBLE,
    credit_score DOUBLE,
    risk_band VARCHAR,
    risk_grade VARCHAR,
    ifrs9_stage VARCHAR,
    watchlist_indicator VARCHAR,
    delinquency_state VARCHAR,
    utilization DOUBLE,
    underwriting_decision VARCHAR,
    default_outcome VARCHAR,
    dq_status VARCHAR NOT NULL,
    source_payload_json VARCHAR NOT NULL,
    loaded_at TIMESTAMP NOT NULL,
    UNIQUE(ingestion_batch_id, source_row_number)
);

CREATE TABLE IF NOT EXISTS staging.stg_historical_event_row (
    staging_event_id VARCHAR PRIMARY KEY,
    ingestion_batch_id VARCHAR NOT NULL,
    snapshot_id VARCHAR NOT NULL,
    source_asset_id VARCHAR NOT NULL,
    source_row_number BIGINT NOT NULL,
    source_entity_id VARCHAR NOT NULL,
    source_facility_id VARCHAR,
    event_type VARCHAR NOT NULL,
    event_date DATE NOT NULL,
    source_column VARCHAR NOT NULL,
    source_event_value VARCHAR,
    dq_status VARCHAR NOT NULL,
    loaded_at TIMESTAMP NOT NULL
);
