CREATE TABLE IF NOT EXISTS core.fact_historical_credit_observation (
    observation_id VARCHAR PRIMARY KEY,
    snapshot_id VARCHAR NOT NULL,
    historical_snapshot_key VARCHAR NOT NULL,
    entity_key VARCHAR NOT NULL,
    facility_key VARCHAR,
    source_asset_id VARCHAR NOT NULL,
    source_row_number BIGINT NOT NULL,
    observation_date DATE,
    reporting_date DATE,
    origination_date DATE,
    maturity_date DATE,
    source_run_id VARCHAR,
    source_model_version VARCHAR,
    pd DOUBLE,
    lgd DOUBLE,
    ead DOUBLE,
    credit_score DOUBLE,
    risk_band VARCHAR,
    risk_grade VARCHAR,
    ifrs9_stage VARCHAR,
    watchlist_indicator VARCHAR,
    delinquency_state VARCHAR,
    utilization DOUBLE,
    underwriting_decision VARCHAR,
    default_outcome VARCHAR,
    evidence_classification VARCHAR NOT NULL,
    loaded_at TIMESTAMP NOT NULL,
    UNIQUE(snapshot_id, entity_key, facility_key)
);

CREATE TABLE IF NOT EXISTS core.fact_historical_credit_event (
    event_id VARCHAR PRIMARY KEY,
    snapshot_id VARCHAR NOT NULL,
    entity_key VARCHAR NOT NULL,
    facility_key VARCHAR,
    source_asset_id VARCHAR NOT NULL,
    source_row_number BIGINT NOT NULL,
    event_type VARCHAR NOT NULL,
    event_date DATE NOT NULL,
    source_column VARCHAR NOT NULL,
    source_event_value VARCHAR,
    provenance_classification VARCHAR NOT NULL,
    loaded_at TIMESTAMP NOT NULL
);
